Enable breaking lines within "words" by breaking on grapheme clusters
go-text/typesetting pull request #71
Opened 2023-05-24 17:16 UTC by whereswaldon

This commit implements wrapping on grapheme cluster boundaries (UAX#29) in addition to our previous word boundary (UAX#14) wrapping. The choice of whether to wrap on grapheme clusters is left up to a new LineBreakPolicy type with three options:

- WhenNecessary: This option will break using grapheme clusters when no word can fit on the line or when it is truncating a word (preserving as many grapheme clusters of the word as possible). This is the default policy.
- Always: This option will break on grapheme clusters whenever possible, fitting as many grapheme clusters as possible on every line.
- Never: This option disables the use of grapheme cluster breaking entirely, and preserves the prior behavior.

As WhenNecessary is the zero value of LineBreakPolicy, consumers of our API will experience a behavior change when updating to this version. Text that previously overflowed its bounds because words were too long will now fit within them. I think that this is going to be an improvement for 95% or more of use cases, so the change is warranted.

This PR is a draft while its prerequisite, #68, is still under review.

2023-05-29 20:27 UTC, andydotxyz commented
> Text that previously overflowed its bounds because words were too long will now fit within them. I think that this is going to be an improvement for 95% or more of use cases, so the change is warranted.

I guess it depends on whether this algorithm is also used to determine space required for text passed.
For example Fyne uses wrapping to know what a minimum would be for width before deciding what space is allocated. If the default was wrap-word then changing the default to be sub-word may not be the expected result.

p.s. what does "UAX#" refer to?

2023-05-29 20:31 UTC, whereswaldon commented
> > Text that previously overflowed its bounds because words were too long will now fit within them. I think that this is going to be an improvement for 95% or more of use cases, so the change is warranted.
> 
> I guess it depends on whether this algorithm is also used to determine space required for text passed. For example Fyne uses wrapping to know what a minimum would be for width before deciding what space is allocated. If the default was wrap-word then changing the default to be sub-word may not be the expected result.

Sure, but that isn't the primary or default use case of the algorithm. Fyne is free to ensure that in the APIs it exposes, it sets the policy to `Never` instead of `WhenNecessary`. I still maintain that the API presented by `go-text` is most ergonomic with this default.

> p.s. what does "UAX#" refer to?

These are standards defining how to delimit segments of text put out by unicode:

- [UAX#14](https://unicode.org/reports/tr14/)
- [UAX#29](https://unicode.org/reports/tr29/)

These two documents define the rules for what constitutes a valid line break.

2023-05-29 20:49 UTC, andydotxyz commented
> Fyne is free to ensure that in the APIs it exposes, it sets the policy to Never instead of WhenNecessary.

For sure, I wasn't meaning to state that it should be otherwise on Fyne's behalf, just indicating another usage in case it helped.

> I still maintain that the API presented by go-text is most ergonomic with this default.

Fair enough, I don't feel strongly. I think I had misremembered that the default wrapping was set as word - but on review that was more implicit, so the change isn't so large as I had thought.

> These are standards defining how to delimit segments of text put out by unicode:

Thanks

2023-05-29 20:51 UTC, whereswaldon commented
I hadn't realized conflicts snuck in on this branch. I should be able to tackle those tomorrow. I suspect they're trivial, so this should be reviewable if you have time.

2023-05-29 21:42 UTC, andydotxyz commented
GitHub is showing a few 100 lines of conflict - but it may be just the way they render overlapping code I'm not sure.

2023-05-31 09:45 UTC, benoitkugler requested changes
Overall this looks good to me, nice work !
Please have a look at #72 for minor suggestions..

2023-05-31 11:45 UTC, whereswaldon commented
What an excellent review @benoitkugler! I really appreciate it.

2023-05-31 13:30 UTC, andydotxyz approved these changes

2023-05-31 14:04 UTC, benoitkugler approved these changes

2023-05-31 14:06 UTC, merged